matrix:
  include:
    - language: ruby
      rvm:
        - 2.7
    - language: ruby
      rvm:
        - 2.6
    - language: go
      go:
        - 1.15.x
    - language: go
      go:
        - 1.14.x
